packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@base-ui/react': ^1.2.0
  '@better-auth/drizzle-adapter': https://pkg.pr.new/better-auth/better-auth/@better-auth/drizzle-adapter@6913
  '@fontsource-variable/inter': ^5.2.8
  '@remixicon/react': ^4.9.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.5.1
  '@tanstack/eslint-plugin-query': ^5.91.4
  '@tanstack/eslint-plugin-router': ^1.155.0
  '@tanstack/react-devtools': ^0.9.5
  '@tanstack/react-form-devtools': ^0.2.15
  '@tanstack/react-form-start': ^1.28.2
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.159.10
  '@tanstack/react-router-devtools': ^1.159.10
  '@tanstack/react-router-ssr-query': ^1.159.10
  '@tanstack/react-start': ^1.159.11
  '@types/node': ^24.10.13
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.4
  babel-plugin-react-compiler: ^1.0.0
  better-auth: beta
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  drizzle-kit: beta
  drizzle-orm: beta
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.8.8
  husky: ^9.1.7
  lint-staged: ^16.2.7
  motion: ^12.34.0
  nanoid: ^5.1.6
  nitro: npm:nitro-nightly@latest
  oxfmt: ^0.32.0
  oxlint: ^1.47.0
  oxlint-tsgolint: ^0.12.2
  postgres: ^3.4.8
  react: ^19.2.4
  react-dom: ^19.2.4
  shadcn: ^3.8.4
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  turbo: ^2.8.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^8.0.0-beta.14
  zod: ^4.3.6

catalogMode: prefer

overrides:
  '@better-auth/drizzle-adapter': https://pkg.pr.new/better-auth/better-auth/@better-auth/drizzle-adapter@6913
  vite: ^8.0.0-beta.14
